name: Build Release Binaries

on:
  release:
    types: [created]

jobs:
  build:
    name: Build for ${{ matrix.os }} (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux builds
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ""
            name: "Linux x64"
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            suffix: ""
            name: "Linux ARM64 (Raspberry Pi 64-bit)"
            use_cross: true
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            suffix: ""
            name: "Linux ARMv7 (Raspberry Pi 32-bit)"
            use_cross: true
          
          # macOS builds
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ""
            name: "macOS x64"
          
          # Windows builds
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: ".exe"
            name: "Windows x64"
          - os: windows-latest
            target: i686-pc-windows-msvc
            suffix: ".exe"
            name: "Windows x86 (32-bit)"
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            suffix: ".exe"
            name: "Windows ARM64"
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      
      # Install cross for ARM Linux targets
      - name: Install cross
        if: matrix.use_cross
        run: cargo install cross
      
      # Build with cross for ARM Linux targets
      - name: Build with cross (ARM Linux)
        if: matrix.use_cross
        run: cross build --release --target ${{ matrix.target }}
      
      # Build with cargo for other targets
      - name: Build with cargo
        if: ${{ !matrix.use_cross }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      
      - name: Prepare artifacts
        shell: bash
        run: |
          ARTIFACTS_DIR=krkr-tts-${{ matrix.target }}
          mkdir -p $ARTIFACTS_DIR
          
          # Copy binaries
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            cp target/${{ matrix.target }}/release/krkr-tts-client.exe $ARTIFACTS_DIR/
            cp target/${{ matrix.target }}/release/krkr-tts-server.exe $ARTIFACTS_DIR/
          else
            cp target/${{ matrix.target }}/release/krkr-tts-client $ARTIFACTS_DIR/
            cp target/${{ matrix.target }}/release/krkr-tts-server $ARTIFACTS_DIR/
          fi
          
          # Copy config
          mkdir -p $ARTIFACTS_DIR/config
          cp -r config/* $ARTIFACTS_DIR/config/
          
          # Copy README and LICENSE
          cp README.md LICENSE $ARTIFACTS_DIR/
      
      - name: Create archive
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            7z a -tzip krkr-tts-${{ matrix.target }}.zip krkr-tts-${{ matrix.target }}
          else
            tar -czvf krkr-tts-${{ matrix.target }}.tar.gz krkr-tts-${{ matrix.target }}
          fi
      
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            krkr-tts-${{ matrix.target }}.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 